spring:
  profiles:
    active: dev
  datasource:
    url: "jdbc:postgresql://127.0.0.1:5432/financial-targets-db"
    username: postgres
    password: G~w<Yq=&fU;93kNLZ
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
  flyway:
    baseline-on-migrate: true
    baseline-version: 1
server:
  port: 8080
  servlet:
    contextPath: /api
  info:
    app:
      name: Financial Targets Incomes Service
      version: '0.0.1-SNAPSHOT'
logging:
  level:
    com.financialtargets.incomes: DEBUG
spring-doc:
  paths-to-match: /**
  swagger-ui:
    use-root-path: true